### PR TITLE
VMware install and secrets specs

### PR DESCRIPTION
**Pull request by erickhan**
These are three YAML files for the setup on VMware. (1) install Portworx with shared storage, (2) install Portworx with local storage, (3) secrets for integration with vSphere.

### CODE REVIEW

**Comment by erickhan** [comment]
Adding files for taking a 3DSnap + CloudSnap in a single step and a separate for restoring from the combined 3DSnap+CloudSnap

**Comment by wallnerryan** [comment]
did you want this open ?

**Comment by erickhan** [comment]
my bad. re-opening.

**Comment by wallnerryan** [comment]
@erickhan can you move this into `specs/vmware/` ? And ill move gke specs into `specs/gke`. So we dont confuse the 3dsnap and other specs across environments.

**Comment by erickhan** [comment]
Updating for consistency as follows:
(1) Moving VMware two install specs into a new specsVMware folder. [no more VMware specs in GKE section]
(2) New Postgres-cloudsnap-3d.md is a version of the POSTGRES.md that describes the workflow [where we use cloudsnap & 3d at the same time].
(3) renamed the jointed cloudsnap & 3dsnap YAMLs to *-cloudsnap-3d.yaml. [before, it was named *-3d-cloudsnap.yaml].

**Comment by wallnerryan** [comment]
LGTM

**Pull request merged**
